### PR TITLE
Fix CuratorColumn image size with px

### LINKED ISSUE #210: CuratorColumn: invalid glide url
Hello, i use CuratorColumn like this

`CuratorColumn::make('preview_image_id')->label('Preview Image')->size(50) or width(50)`
and this is url what we have
`/curator/articles/article-1.jpg?w=50px&h=40px&fit=crop&fm=webp&s=818c581169f60065dd45164ff0048c58`
I think it happens because **ImageColumn** adds `px` to width and height
but `w=50px` is invalid parameter for glide

### PR DESCRIPTION
**Pull request by howdu**
Fixes https://github.com/awcodes/filament-curator/issues/210

Also adds `resolution` to allow the resized image to be upscaled for HD quality. 
```php
CuratorColumn::make()
  ->size(100)
  ->resolution(2);
```

### CODE REVIEW

**Comment by lotarbo** [comment]
@howdu  hi, thank you for your fix, but i think It's now safe, because we can pass string `60em` 
mb just use `(int)` ?

**Comment by howdu** [comment]
@lotarbo thanks yeah I thought that too would be cleaner too, but Glide uses only px and it's Filament `ImageColumn::getWidth()` which adds the 'px' so the reason I went with the str_replace. 

Let's see what @awcodes thinks.

**Comment by lotarbo** [comment]
@howdu i mean we can do this `->width('50em')` and `ImageColumn::getWidth()` return `50em`

**Comment by howdu** [comment]
> @howdu i mean we can do this `->width('50em')` and `ImageColumn::getWidth()` return `50em`

I think that would be the same issue where Glide wouldn't resize the image because it [only accepts px ](https://glide.thephpleague.com/2.0/api/size/#width-w
)

**Comment by lotarbo** [comment]
@howdu yeah i know, it creates url
`article-1.jpg?w=50em&h=50em&fit=crop&fm=webp&s=e6f52076e0f547afebb787baddfcc271`
and glide doesn't crop image
i only think if we pass int in all situation
`article-1.jpg?w=50&h=50&fit=crop&fm=webp&s=e6f52076e0f547afebb787baddfcc271`
but you right, maybe better do nothing in this)

**Comment by awcodes** [comment]
Let's go with (int). It's be faster and safer that a preg_replace.

Thanks.

**Comment by awcodes** [comment]
Awesome. Thanks again.

**Pull request merged**
