### PR TITLE
Feat: filter media picker items base on accept file types

### PR DESCRIPTION
**Pull request by aymanalareqi**

### CODE REVIEW

**Comment by aymanalareqi** [comment]
@awcodes 
You can now check this PR and merge it, if everything well

**Review by awcodes — CHANGES_REQUESTED** [review]
1. Please remove all class name changes that are not necessary to functionality changes.
2. Remove changes to src/Curator.php (this was already in your other PR and has already been merged)

Please take care of those so I can get a better understanding of everything you're trying to do.

Thanks.

**Comment by awcodes** [comment]
I hate to do this to you, but I had to merge a pr that is going to cause a conflict with your MediaController. Can you pull down the latest version and update that? Sorry.

**Comment by aymanalareqi** [comment]
> I hate to do this to you, but I had to merge a pr that is going to cause a conflict with your MediaController. Can you pull down the latest version and update that? Sorry.

no problem

**Comment by awcodes** [comment]
Any update on this?

**Comment by awcodes** [comment]
Thanks for your work on this, but I've decided to go in a different direction with this feature and it will be in the next release.

Please feel free to submit more PRs in the future.

**Pull request closed without merging**
