### PR TITLE
Feature: Path generators

### PR DESCRIPTION
**Pull request by mynamespace**
It's possible to define a path generator in config, a simple class that inherits from PathGenerator interface that returns the directory used to store the media file and thumbnails inside the configured disk. The directory can be dynamic and based on other system parameters like the current date, the current user, or other configurations.
There are two example generators: DatePathGenerator and UserPathGenerator.
Note: we do not have the Media model at the time of storing the file, so we can't use its attributes to define the directory.

### CODE REVIEW

**Comment by awcodes** [comment]
Thanks. I'll try to look this over this weekend.

**Comment by awcodes** [comment]
This looks good.

One thing, though. Can you also delete the created directories if they are empty after a file has been deleted?

**Comment by mynamespace** [comment]
I think it's no problem extending your deleted() model event. I'll work on it tomorrow :)

**Comment by mynamespace** [comment]
Done. I've added a couple of missing translated labels, too.

**Comment by awcodes** [comment]
Thank you. Greatly appreciate it.

**Pull request merged**
