### PR TITLE
Add title and directory to searchable

### PR DESCRIPTION
**Pull request by martinmildner**

### CODE REVIEW

**Comment by awcodes** [comment]
Can you explain the need for this?

I think this would be better as either implementing a custom MediaResource or as a configurable option somewhere instead of being hard coded.

**Comment by martinmildner** [comment]
Hello Adam,

I've been observing some customers while they were working, and they were "surprised" that their file couldn't be found even though they entered a title.

Search for the "directory": We sometimes store data for individual models in corresponding subfolders (e.g. media/articles/234). This way, you could easily jump to "Media" and display the files uploaded for this model. But you're right, that would be better placed in the settings... I'll change the pull request...

**Comment by awcodes** [comment]
Let me know when you get it updated.

**Comment by awcodes** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
