### PR TITLE
Fix: picker not working in modal forms

### PR DESCRIPTION
**Pull request by awcodes**

### CODE REVIEW

**Comment by chosten** [comment]
There is now a blank space at the bottom of the page because of the `inline-block` class used by the Filament modal.
Not sure what's the best way to get rid of that.

**Comment by awcodes** [comment]
@chosten this has been fixed in the latest release. Thanks.

**Comment by chosten** [comment]
There is another problem related to this PR. 
If the CuratorPicker is conditionally displayed, with a reactive checkbox for example, once it is hidden there is a JS error in the console. `Uncaught Snapshot missing on Livewire component with id: ucxxxxx`
It's not possible to open the modal anymore after this.

**Comment by awcodes** [comment]
Ugh. Ok. Thanks, I'll see about a fix soon. It may require a potential breaking change though. :(

**Pull request merged**
